// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Vl6vac0ezDzCtRZ0MlkcHYk57BvRC1Y',
    appId: '1:480725532761:web:645c7f8e82a4f7ea29f148',
    messagingSenderId: '480725532761',
    projectId: 'salvavidas-6457d',
    authDomain: 'salvavidas-6457d.firebaseapp.com',
    storageBucket: 'salvavidas-6457d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCla8TCqjDXKCYCpTMffPolxAdgQi96Dx0',
    appId: '1:480725532761:android:67ee7e935d79b4f629f148',
    messagingSenderId: '480725532761',
    projectId: 'salvavidas-6457d',
    storageBucket: 'salvavidas-6457d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmMQi17PIHwA-YaYUxRpfL94rgR-cN-iA',
    appId: '1:480725532761:ios:496bc14ad555437329f148',
    messagingSenderId: '480725532761',
    projectId: 'salvavidas-6457d',
    storageBucket: 'salvavidas-6457d.appspot.com',
    androidClientId: '480725532761-431mo9fll9bd7kkd8eop9jv0ilqo189j.apps.googleusercontent.com',
    iosClientId: '480725532761-ojldk9vmn0gibg4co5a64n1ta4lejc34.apps.googleusercontent.com',
    iosBundleId: 'com.example.salvavidas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmMQi17PIHwA-YaYUxRpfL94rgR-cN-iA',
    appId: '1:480725532761:ios:496bc14ad555437329f148',
    messagingSenderId: '480725532761',
    projectId: 'salvavidas-6457d',
    storageBucket: 'salvavidas-6457d.appspot.com',
    androidClientId: '480725532761-431mo9fll9bd7kkd8eop9jv0ilqo189j.apps.googleusercontent.com',
    iosClientId: '480725532761-ojldk9vmn0gibg4co5a64n1ta4lejc34.apps.googleusercontent.com',
    iosBundleId: 'com.example.salvavidas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0Vl6vac0ezDzCtRZ0MlkcHYk57BvRC1Y',
    appId: '1:480725532761:web:450fe175d0694a5329f148',
    messagingSenderId: '480725532761',
    projectId: 'salvavidas-6457d',
    authDomain: 'salvavidas-6457d.firebaseapp.com',
    storageBucket: 'salvavidas-6457d.appspot.com',
  );
}
